name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install system packages
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y \
          python3 python3-pip python3-setuptools python3-wheel \
          build-essential git zip unzip openjdk-11-jdk \
          libncurses5 libncurses5:i386 libstdc++6 libstdc++6:i386 \
          zlib1g zlib1g:i386

    - name: Install Python packages
      run: |
        pip install --upgrade pip cython
        pip install flet buildozer

    - name: Prepare project
      run: |
        mkdir app_sismos_android
        cd app_sismos_android
        cp ../main.py main.py
        python -m buildozer init

    - name: Build APK
      run: |
        cd app_sismos_android
        python -m buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-sismos-cdmx-apk
        path: app_sismos_android/bin/*.apk
